### PR TITLE
Support for jQuery Mobile 1.3.X

### PR DESCRIPTION
**Pull request by indrimuska**
Based on the same wrapper for jQM 1.4+.
Full demo at http://jsbin.com/indrimuska/54/edit.
## 

notes: Added a second css sheet (jquery.mobile.datepicker.theme.css) to use some standard jqm styles.

### CODE REVIEW

**Comment by arschmitz** [comment]
Thanks for working on this there are several big changes needed though first the js needs a much different widget structure to properly support 1.3 see https://github.com/jquery/jquery-mobile/blob/1.3-stable/js/widgets/navbar.js for reference take special notice of the widget declaration at the top and the event binding at the bottom also in 1.3 its necessary to  work with data attribute options and to support auto initialization.

The css should all be one file also

And this should be a 1.3 branch separate from 1.4 not a folder within the main branch if you can work on making these updates ill take another look when your done.

**Comment by indrimuska** [comment]
Thank you @arschmitz, I tried to follow the main guidelines at widget factory and now the widget autoinitializes itself and work perfectly with data attribute options.
I also merged all the style into one css file, as you said.

Working demo here: http://jsbin.com/indrimuska/56/edit

**Comment by arschmitz** [comment]
@indrimuska this looks much better ill need to do some testing first but looks good one small thing can you please change the copyright back to my name please :)

**Comment by indrimuska** [comment]
Ok, give it a try and tell me what you think about.

**Comment by arschmitz** [comment]
@indrimuska hey sorry i never got to a better review on this i ended up switching focus to a complete re-write and simplification. Because the re-write is so different this pr is no longer relavant feel free to look at new version and see if you still think 1.3.x support is worth it

**Pull request closed without merging**
