### PR TITLE
Support for theme attribute (data-theme)

### PR DESCRIPTION
**Pull request by indrimuska**
Theme support DEMO: http://jsbin.com/indrimuska/33/edit

### CODE REVIEW

**Comment by indrimuska** [comment]
Sorry @arschmitz, but I don't know how to separate every pull request, and every time I commit and push to my master branch GitHub merges all the requests together. I can only stop commit and wait you to review this req.

**Comment by arschmitz** [comment]
@indrimuska thanks for submitting this i do have one question about why you are changing the css here it seems unrelated. Also there is already an open pr for adding theme from someone else i already accepted prior to you submitting this its the same except for the css change so i wanted to ask about this.

**Comment by indrimuska** [comment]
I completely agree to you, but, as already said, I don't know how to open different prs because github merges all my new commits together in this pr.

Anyway, there's a little difference in my code for supporting theme, and it's about a different choice of the header theme: I left the header in a a-style (the white version) also when user set data-theme="b".
You can see the differences in this screenshot:

screenshot

I suggest to create an extra attribute for selecting header's theme, something like data-headertheme.

**Comment by arschmitz** [comment]
@indrimuska thanks for explaining however i think im going to go with keeping it all the same theme though. there is one main reason for this in that jQuery mobile is currently planning on dropping swatches and different themes in the near future making this option obsolete. 

sorry i also now see your explination of the css. yes i agree that should be fixed. 

as pr's as separating prs you need to use branches make each pr on a different branch.

**Comment by indrimuska** [comment]
Thanks for your help.
I'll update the code to take the same theme in the header bar.

**Pull request closed without merging**
